# Generated by Django 4.0.3 on 2022-04-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_blogpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
