# Generated by Django 4.0.3 on 2022-04-06 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_remove_blogpost_likes_blogpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='dislikes',
            field=models.ManyToManyField(related_name='blog_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
