# Generated by Django 4.0.3 on 2022-04-07 22:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogpost_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
