# Generated by Django 4.0.3 on 2022-04-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpost_blogpost_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(default='Click "Read More" to view post.', max_length=255),
        ),
    ]
