# Generated by Django 4.0.3 on 2022-04-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogpost_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
