# Generated by Django 4.0.3 on 2022-05-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_blogpost_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pinterest_url',
            new_name='linkedin_url',
        ),
    ]
