# Generated by Django 4.0.3 on 2022-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_pinterest_url_profile_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='snippet',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
