# Generated by Django 4.0.3 on 2022-06-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default='1')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('author', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('website_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Project',
            },
        ),
    ]
