# Generated by Django 4.0.3 on 2022-04-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='order',
            field=models.IntegerField(default='1'),
        ),
    ]
