# Generated by Django 4.0.3 on 2022-04-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projects_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='website_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
