# Generated by Django 4.0.3 on 2022-05-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projects_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/projects'),
        ),
    ]
