# Generated by Django 4.0.3 on 2022-05-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projects_header_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project'},
        ),
    ]
