# Generated by Django 4.0.3 on 2022-06-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_projects_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='snippet',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
